name: Manual Implementation Trigger

on:
  workflow_dispatch:
    inputs:
      spec_id:
        description: 'Spec ID (e.g., 001-feature-name)'
        required: true
        type: string

permissions:
  contents: write
  pull-requests: write
  issues: write
  id-token: write

jobs:
  trigger-implementation:
    uses: omni-stove/specify-ci/.github/workflows/manual-implement-reusable.yml@main
    with:
      spec_id: ${{ inputs.spec_id }}
      specs_dir: 'specs'
      base_branch: 'main'
    secrets:
      claude_code_oauth_token: ${{ secrets.CLAUDE_CODE_OAUTH_TOKEN }}
