name: Tasks Changed

on:
  pull_request:
    types: [closed]
    paths:
      - 'specs/**/tasks.md'
    branches:
      - main

permissions:
  contents: write
  pull-requests: write
  issues: write
  id-token: write

jobs:
  execute-tasks:
    if: github.event.pull_request.merged == true
    uses: omni-stove/specify-ci/.github/workflows/tasks-changed-reusable.yml@main
    with:
      specs_dir: 'specs'
      base_branch: 'main'
    secrets:
      claude_code_oauth_token: ${{ secrets.CLAUDE_CODE_OAUTH_TOKEN }}
