name: Tasks Changed (Reusable)

on:
  workflow_call:
    inputs:
      specs_dir:
        description: 'Directory containing specs (default: specs)'
        required: false
        type: string
        default: 'specs'
      base_branch:
        description: 'Base branch to check merges into (default: main)'
        required: false
        type: string
        default: 'main'
      claude_args:
        description: 'Additional Claude Code arguments'
        required: false
        type: string
        default: '--allowedTools "Bash,SlashCommand,Edit,Read,Write,Glob,Grep"'
      implement_command:
        description: 'Specify implement command (default: /implement)'
        required: false
        type: string
        default: '/implement'
    secrets:
      claude_code_oauth_token:
        description: 'Claude Code OAuth token'
        required: true

permissions:
  contents: write
  pull-requests: write
  issues: write
  id-token: write

jobs:
  detect-and-implement:
    uses: ./.github/workflows/specify-implement-reusable.yml
    with:
      detect_from_git_diff: true
      specs_dir: ${{ inputs.specs_dir }}
      base_branch: ${{ inputs.base_branch }}
      claude_args: ${{ inputs.claude_args }}
      implement_command: ${{ inputs.implement_command }}
    secrets:
      claude_code_oauth_token: ${{ secrets.claude_code_oauth_token }}
